from dspy.gsm8k import GSM8KTask
from dspy.hotpotqa import HotPotQATask
from dspy.scone import ScoNeTask
from dspy.tweet import TweetTask
from dspy.tweet_metric import TweetMetricTask
from dspy.heart_disease import HeartDiseaseTask
from dspy.hotpotqa_conditional import HotPotQAConditionalTask
from dspy.hover import HoverRetrieveDiscrete
from dspy.iris_typo import IrisTypoClassifierTask
from dspy.iris import IrisClassifierTask